### ISSUE TITLE
Deduplicate results near the prime meridian

### ISSUE THREAD

**Issue by sgillies** [mapbox/cardboard#59]
As I said in today's scrum, I'm adding tests near the prime meridian in an issue54 branch. We're getting duplicate features.

I'm thinking deduplication is the immediate fix with work in the near future to avoid duplicate results. @rclark @mick cardboard is where to dedupe, right? It's only dyno between us and AWS from cardboard?

Details below:

```
# query for line crossing 0 lon
ok 120 inserted
ok 121 {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"}]}
not ok 122 {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"},{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"},{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"},{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"}]}
  ---
    file:   /Users/sean/code/cardboard/node_modules/queue-async/queue.js
    line:   46
    column: 21
    stack:
      - getCaller (/Users/sean/code/cardboard/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/Users/sean/code/cardboard/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/Users/sean/code/cardboard/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/Users/sean/code/cardboard/node_modules/tap/lib/tap-test.js:87:16)
      - /Users/sean/code/cardboard/test/index.js:520:23
      - /Users/sean/code/cardboard/index.js:262:17
      - notify (/Users/sean/code/cardboard/node_modules/queue-async/queue.js:46:21)
      - Object.q.awaitAll (/Users/sean/code/cardboard/node_modules/queue-async/queue.js:68:25)
      - resolveFeatures (/Users/sean/code/cardboard/index.js:323:11)
      - /Users/sean/code/cardboard/index.js:260:13
    found:  4
    wanted: 1
  ...
ok 123 {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"}]}
not ok 124 {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"},{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"},{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"},{"type":"Feature","properties":{},"geometry":{"coordinates":[[-1,1],[1,1]],"type":"LineString"},"id":"ci079jsy70012rm2ha1ooft6e"}]}
  ---
    file:   /Users/sean/code/cardboard/node_modules/queue-async/queue.js
    line:   46
    column: 21
    stack:
      - getCaller (/Users/sean/code/cardboard/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/Users/sean/code/cardboard/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/Users/sean/code/cardboard/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/Users/sean/code/cardboard/node_modules/tap/lib/tap-test.js:87:16)
      - /Users/sean/code/cardboard/test/index.js:520:23
      - /Users/sean/code/cardboard/index.js:262:17
      - notify (/Users/sean/code/cardboard/node_modules/queue-async/queue.js:46:21)
      - Object.q.awaitAll (/Users/sean/code/cardboard/node_modules/queue-async/queue.js:68:25)
      - resolveFeatures (/Users/sean/code/cardboard/index.js:323:11)
      - /Users/sean/code/cardboard/index.js:260:13
    found:  4
    wanted: 1
  ...
ok 125 passed queries
# teardown
```
